### ISSUE TITLE
⌘+drag not working

### ISSUE THREAD

**Issue by jariz** [mxcl/Workbench#16]
Hiya, great tool! However, not that keen on having it in my menubar at all times.
Bartender can't seem to control it, however. 

Are you doing something non-standard or something?
Haven't really ran into any apps that bartender can't handle.

![](https://jari.lol/NXnjlz3rW1.png)

**Comment by mxcl** [comment]
We’re not doing anything non-standard.

**Comment by jariz** [comment]
I'll shoot them a message, thanks.

**Comment by bensurtees** [comment]
Hi, I am the developer of Bartender, the issue is that Bartender uses the macOS default behaviour of ⌘+dragging menu items to reposition/order them in the menu bar (try this on other menu items, they should drag and reposition themselves, except Notification Center which isn't allowed to move).
This does not work with workbench (regardless of Bartender running) this is because in workbench you are overriding this behaviour by catching events before they go through the StatusItemWindow sendEvent (which handles this) by using a localeventmonitor (which gets the events first), which is okay, but you just want to check to see if ⌘ is pressed (check the event. modifierFlags) and allow that event to pass through (return event) without triggering self?.onStatusBarItemClicked()
You should then get the dragging behaviour back, and as an added bonus Bartender will work with it.

Let me know if you need more info or anything.

Ben

**Comment by bensurtees** [comment]
I created a pull request with what I believe should be a fix ( I didn't compile workbench to test it)

**Comment by mxcl** [comment]
My bad, we *were* doing something non-standard. New build on its way.

**Comment by mxcl** [comment]
Workbench 1.0.1 is available and I have confirmed you can now ⌘-drag.

To force an update hold ⌥ and click the cog menu, the item “Check for updates” will appear. The new version will download and restart, you can verify the version is 1.0.1 by looking in the bottom left of the popup.
